#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=00:15:00
#PBS -q fast
#PBS -t 0-99
#PBS -m n

# Ensure that GFORTRAN output occurs as written instead of all C/C++ followed by
# FORTRAN
export GFORTRAN_UNBUFFERED_ALL='y'

ix=${PBS_ARRAYID}

T=1
J=12
IVType=Char

for inFile in /gpfs/pads/projects/CI-SES000069/data/blp/arm.T${T}.J${J}/rep${ix}/config/Re.${IVType}.*
do
  echo
  echo '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
  echo '====>>>> BLP - solving with replication =' $ix
  echo '->->->   Resolving with original optimum'
  echo "         Using ${IVType} instruments"
  echo "         T = ${T}, J = ${J} "
  echo "         Config :" ${inFile}
  echo '<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'
  echo
  /gpfs/pads/projects/CI-SES000069/sbox/blpcpp/src/blpDriver -f ${inFile}
done

